FROM python:3.12-slim

WORKDIR /flask_app

COPY . .

ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["flask", "--app", "flask_app.app", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
